language: R
sudo: false
cache: packages

warnings_are_errors: false

pandoc: false

os:
  - linux

script:
  - export _R_CHECK_FORCE_SUGGESTS_=0
  - mkdir Rchecks
  - Rscript -e 'devtools::install_github("kylebmetrum/dmutate")'
  - Rscript -e 'devtools::install_github("metrumresearchgroup/mrgsolve")'
  - Rscript -e 'devtools::install_github("kylebaron/optimhelp")'
  - make travis
